export enum GradeJobTypes {
  LIST_STUDENTS_REQUEST = "LIST_STUDENTS_REQUEST",
  LIST_STUDENTS_REQUEST_SUCCESS = "LIST_STUDENTS_REQUEST_SUCCESS",
  LIST_STUDENTS_REQUEST_FAIL = "LIST_STUDENTS_REQUEST_FAIL",

  UPDATE_CALIFICATION_STUDENT = "UPDATE_CALIFICATION_STUDENT",
  UPDATE_CALIFICATION_STUDENT_SUCCESS = "UPDATE_CALIFICATION_STUDENT_SUCCESS",
  UPDATE_CALIFICATION_STUDENT_FAIL = "UPDATE_CALIFICATION_STUDENT_FAIL",

  EDIT_UPDATE_CALIFICATION = "EDIT_UPDATE_CALIFICATION",
}
