export enum StudentTypes {
  COURSE_ALL_REQUEST = "COURSE_ALL_REQUEST",
  COURSE_ALL_REQUEST_SUCCESS = "COURSE_ALL_REQUEST_SUCCESS",
  COURSE_ALL_REQUEST_FAIL = "COURSE_ALL_REQUEST_FAIL",

  GET_STUDENTS_REQUEST = "GET_STUDENTS_REQUEST",
  GET_STUDENTS_REQUEST_SUCCESS = "GET_STUDENTS_REQUEST_SUCCESS",
  GET_STUDENTS_REQUEST_FAIL = "GET_STUDENTS_REQUEST_FAIL",

  UPDATE_STUDETS_REQUEST = "UPDATE_STUDETS_REQUEST",
  UPDATE_STUDETS_REQUEST_SUCCESS = "UPDATE_STUDETS_REQUEST_SUCCESS",
  UPDATE_STUDETS_REQUEST_FAIL = "UPDATE_STUDETS_REQUEST_FAIL",

  EDIT_STUDENT = "EDIT_STUDENT",

  SELECTED_COURSE = "SELECTED_COURSE",

  DELETE_STUDENT_REQUEST = "DELETE_STUDENT_REQUEST",
  DELETE_STUDENT_REQUEST_SUCCESS = "DELETE_STUDENT_REQUEST_SUCCESS",
  DELETE_STUDENT_REQUEST_FAIL = "DELETE_STUDENT_REQUEST_FAIL",
}
