export enum AsistenciaTypes {
  LIST_ASIST_REQUEST = "LIST_ASIST_REQUEST",
  LIST_ASIST_REQUEST_SUCCESS = "LIST_ASIST_REQUEST_SUCCESS",
  LIST_ASIST_REQUEST_FAIL = "LIST_ASIST_REQUEST_FAIL",

  UPDATE_STUDENT_ASIST_REQUEST = "UPDATE_STUDENT_ASIST_REQUEST",
  UPDATE_STUDENT_ASIST_REQUEST_SUCCESS = "UPDATE_STUDENT_ASIST_REQUEST_SUCCESS",
  UPDATE_STUDENT_ASIST_REQUEST_FAIL = "UPDATE_STUDENT_ASIST_REQUEST_FAIL",

  EDIT_STUDENT_ASIST = "EDIT_STUDENT_ASIST",
}
